#! /bin/sh

bspc monitor -d • • • • • • •
#bspc monitor -d 1 2 3 4 5 6 7 8 9

# change bsp layout to master and stack
bsp-layout set tiled 1 &

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap 10
bspc config top_padding 30
bspc config left_padding 15
bspc config right_padding 15
bspc config bottom_padding 30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#D23D3D"
bspc config normal_border_color "#222D32"
bspc config border_width 3

bspc config focus_follows_pointer true

# Development
# bspc rule -a kitty desktop='^1'

# Browsers

bspc rule -a qutebrowser desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Luakit desktop='^2'
bspc rule -a chromium desktop='^2'
bspc rule -a Chromium desktop='^2'
bspc rule -a google-chrome desktop='^2'
bspc rule -a Google-chrome desktop='^2'

# Text Processors

bspc rule -a Evince desktop='^3' follow=on
bspc rule -a Zathura desktop='^3' follow=on
bspc rule -a Gedit desktop='^3' follow=on
bspc rule -a UXTerm desktop='^3' follow=on
bspc rule -a libreoffice desktop='^3' follow=on
bspc rule -a Zeal desktop='^3' follow=on

# File Management

bspc rule -a org.gnome.Nautilus desktop='^4' follow=on
bspc rule -a Spacefm desktop='^4' follow=on
bspc rule -a Pcmanfm desktop='^4' follow=on
bspc rule -a Thunar desktop='^4' follow=on

# Music

bspc rule -a Audacity desktop='^5' follow=on
bspc rule -a spotify-qt desktop='^5' follow=on

# Torrent Management

bspc rule -a qBittorrent desktop='^6' follow=on

# Image and Video Manipulation

bspc rule -a Inkscape desktop='^7' follow=on
bspc rule -a Gimp-2.10 desktop='^7' follow=on
bspc rule -a openshot-qt desktop='^7' follow=on

# Warning

bspc rule -a Gparted desktop='^8' follow=on

bspc rule -a mpv state=floating rectangle=670x430+500+92
bspc rule -a Sakura state=floating rectangle=650x430+500+92 sticky=on
bspc rule -a Nitrogen state=floating rectangle=620x440+90+10 sticky=on
bspc rule -a Nsxiv state=floating rectangle=770x530+540+392
bspc rule -a nsxiv state=floating rectangle=770x530+540+392
bspc rule -a Ristretto state=floating rectangle=770x530+540+392
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

# startup apps

~/.config/autostart/autostart.sh

sakura -name Scratchpad
bspc rule -a Scratchpad sticky=on state=floating layer=above


## Define the scratchpad window
#bspc rule -a \*:sakura:scratchpad state=floating hidden=on

## Assign the scratchpad window to all desktops
#bspc rule -a \*:sakura:scratchpad state=floating sticky=on
#bspc node \-g hidden=on

